//Use this to manually modify the SQL script generated by EF Core. This adds an additional foreign key with GuidId to each table.
//EF Core is giving a fit when we ask it to do this automatically. This is a workaround.

//--ALTER TABLE Address
//--ADD CONSTRAINT FK_Address_Contact_ContactGuidId
//--FOREIGN KEY (ContactGuidId)
//--REFERENCES Contacts(ContactGuidId);

//--ALTER TABLE Contacts
//--ADD CONSTRAINT FK_Contact_Candidate_CandidateGuidId
//--FOREIGN KEY (CandidateGuidId)
//--REFERENCES Contacts(CandidateGuidId);

//--ALTER TABLE Education
//--ADD CONSTRAINT FK_Education_MoreDetail_MoreDetailGuidId
//--FOREIGN KEY (MoreDetailGuidId)
//--REFERENCES MoreDetail(MoreDetailGuidId)


//--ALTER TABLE Employment
//--ADD CONSTRAINT FK_Employment_MoreDetail_MoreDetailGuidId
//--FOREIGN KEY (MoreDetailGuidId)
//--REFERENCES MoreDetail(MoreDetailGuidId)

//--ALTER TABLE Income
//--ADD CONSTRAINT FK_Income_MoreDetail_MoreDetailGuidId
//--FOREIGN KEY (MoreDetailGuidId)
//--REFERENCES MoreDetail(MoreDetailGuidId)

//--ALTER TABLE MoreDetail
//--ADD CONSTRAINT FK_MoreDetail_Candidate_CandidateGuidId
//--FOREIGN KEY (CandidateGuidId)
//--REFERENCES Candidates(CandidateGuidId);


//--ALTER TABLE Photos
//--ADD CONSTRAINT FK_Photos_Candidate_CandidateGuidId
//--FOREIGN KEY (CandidateGuidId)
//--REFERENCES Candidates(CandidateGuidId);